---

- name: create a elasticsearch group
  group:
    name: elasticsearch
    state: present
 
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  become: true

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  become: true

- name: Copy Elasticsearch.yml file
  template:
    src: "{{ elasticsearch }}"
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0640

#- name: Copy Limits.conf file
#  template:
#    src: "{{ limits }}"
#    dest: /etc/security/limits.conf 
#    owner: root
#    group: elasticsearch
#   mode: 0640

#- name: Copy Common-Session File to Pam.d
#  template:
#    src: "{{ common_session }}"
#    dest: /etc/pam.d/common-session
#    owner: root
#    group: elasticsearch
#    mode: 0640

#- name: Copy common-session-noninteractive file to pam.d
#  template:
#    src: "{{ common_session_ni }}"
#    dest: /etc/pam.d/common-session-noninteractive
#    owner: root
#    group: elasticsearch
#   mode: 0640

- name: copy jvm.option file to /etc
  template:
    src: "{{ jvm_options }}"
    dest: /etc/elasticsearch/jvm.options
    owner: root
    group: elasticsearch
    mode: 0640

- name: Start Elasticsearch.
  service: name=elasticsearch state=started enabled=yes
  become: true
  when: ansible_os_family == 'Debian'

- name: Start Elasticsearch
  systemd:
    name: elasticsearch
    state: started
    enabled: true
  become: true
  when: ansible_os_family == 'RedHat'

#- name: Make sure Elasticsearch is running before proceeding.
#  wait_for: host={{ elasticsearch_network_host }} port={{ elasticsearch_http_port }} delay=3 timeout=300
