---

- name: To download  elasticsearch
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch 
    state: present
#  get_url:
#    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.3.deb
#    dest: /root/

- name: To install elasticsearch
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/5.x/apt stable main'
    state: present
  #apt:
  #  deb: /root/elasticsearch-5.6.3.deb
   # state: present
- name: Update cache...
  apt:
    update_cache: yes

- stat: path=/etc/elasticsearch
  register: elasticsearch

- name: Installing Kibana
  apt: name=elasticsearch state=installed
  when: not elasticsearch.stat.exists

    
- name: update the defaults
  command: "update-rc.d elasticsearch defaults"
    
- name: To Configure elastic
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  tags:
    - els
    
- name: To set memory size for java options
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
    
- name: To start elasticsearch
  service: name=elasticsearch state=restarted


