---

- name: To download  elasticsearch
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.1.deb
    dest: /root/

- name: To install elasticsearch
  apt:
    deb: /root/elasticsearch-5.5.1.deb
    state: present
    
- name: update the defaults
  command: "update-rc.d elasticsearch defaults"
    
- name: To Configure elastic
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  tags:
    - els
    
- name: To set memory size for java options
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
    
- name: To start elasticsearch
  service: name=elasticsearch state=restarted


